static-frame/static-frame

- README.rst
Making explicit that when installing from conda, static-frame needs to use conda-forge channel. I guess it's assumed to be in the user settings, but that's probably not the case for most users.
> Specify channel in conda installation instructions

- static_frame/__main__.py
Now, running `python -m static_frame` or `ipython -m static_frame` drops you into an interactive interpreter with `sf`, `np`, and (if installed) `pd` pre-loaded. Here is what that looks like (in each case, the user hasn't interacted yet):
```
$ python -m static_frame
Python 3.7.3 (default, Jun  7 2019, 15:55:34) 
[GCC 5.4.0 20160609] on linux
>>> import numpy as np  # 1.15.1
>>> import pandas as pd  # 0.23.4
>>> import static_frame as sf  # 0.3.5-dev
>>> 
```
`IPython` gets to keep its colored output (can't see it here, obviously):
```
$ ipython -m static_frame
------> import numpy as np  # 1.15.1
------> import pandas as pd  # 0.23.4
------> import static_frame as sf  # 0.3.5-dev
Python 3.7.3 (default, Jun  7 2019, 15:55:34) 
Type 'copyright', 'credits' or 'license' for more information …
```
> python -m static_frame

- requirements-test.txt
`sphinx-jinja==0.3.0` is listed twice in the `requirements-test.txt` file.  Possibly related to the build failure earlier, but certainly worth cleaning up in any case.
> Removing one instance of package listed twice

- static_frame/core/index_base.py
- static_frame/test/unit/test_index.py
- static_frame/test/unit/test_index_hierarchy.py
As requested, this PR implements `__reversed__` in the `IndexBase` base class.
I messed up my rebase on the original branch, so I just deleted it and created a new one.  Here is the conversation history from the original branch. https://github.com/InvestmentSystems/static-frame/pull/66
> IndexBase.__reversed__

- static_frame/core/frame.py
- static_frame/core/series.py
- static_frame/test/unit/test_frame.py
- static_frame/test/unit/test_series.py
A continuation of PR https://github.com/InvestmentSystems/static-frame/pull/66 (responding to Issue https://github.com/InvestmentSystems/static-frame/issues/62), the following implements` __reversed__` for both a Series and a Frame and provides unit tests.
> Series.__reversed__ / Frame.__reversed__

- static_frame/test/property/test_frame.py
Temporarily 'fixes' the `test_frame_isin` property test by skipping `np.datetime64` and `np.timedelta64` types. I created issue #132 to make sure it doesn't permanently remain skipped.
> 'Fix' property test by ignoring date cases. Is referenced by issue #132

- static_frame/core/frame.py
- static_frame/core/util.py
- static_frame/test/unit/test_frame.py
- static_frame/test/unit/test_series.py
It might hit performance, but it seems the safest way to support pandas 1.0.0 ExtensionArray.
> Fix Frame and Series from_pandas() pandas >1.0.0 issues

- static_frame/core/index.py
- static_frame/core/index_base.py
- static_frame/core/index_hierarchy.py
- static_frame/core/util.py
- static_frame/test/property/test_util.py
- static_frame/test/unit/test_index.py
- static_frame/test/unit/test_index_hierarchy.py
- static_frame/test/unit/test_util.py
Adds logic to handle index differences. (Implements feature request #118)
The only change to the existing logic (outside of my additions), is that when `func` is called now, it is passed the `assume_unique` kwarg for `np.setdiff1d` and `np.intersect1d` calls (`np.union1d` does not have that option). Previously that kwarg was not being passed in. Here is the code snippet that performs that:
```python3
func_kwargs = {} if is_union else dict(assume_unique=assume_unique) 
return func(array, other, **func_kwargs)
```
Other observations:
- Order is not being preserved as the docstrings suggest. The calls to `frozenset` are unordered, which means when that branch is hit, order promises are lost. I refrained from addressing that in this PR in order to keep the changes atomic.
- `nan`s do not seem …
> Issue #118: Adds index difference method

- static_frame/test/property/test_util.py
Per the failure in this test run, https://travis-ci.org/github/InvestmentSystems/static-frame/jobs/682130530, this PR addresses an issue with the test `test_setdiff1d`.
Basically, the old test was naively converting all arrays to python sets, resulting in loss of float precision. This change will now compare `post` against the result from a direct `np.setdiff1d` call when the inputs are numbers, as that is the expected behavior.
> Fixes edge hypothesis failure in test_setdiff1d

- static_frame/core/type_blocks.py
- static_frame/test/property/test_frame.py
There is a sneaky reference cycle happening in the creation of type_blocks. Essentially, every type_blocks instance has an attribute `iloc` that contained a reference to an instance of `InterfaceGetItem`, which in turn has a reference to the type_blocks instance itself. This meant that when a frame was deleted, it's underlying type_block structure would hang around, since it was still referenced by the `InterfaceGetItem` instance, which itself was referenced by the type_blocks instance, which was reference by the `InterfaceGetItem` instance, and on and on and on. (Many thanks to @brandtbucher for helping to isolate this bug).
Here is an interesting example of how this reference cycle could lead to memory issues:
```python3
import gc
size = 10_000
f = …
```
> Fixes type_blocks reference cycle.

- .gitignore
- static_frame/core/store_sqlite.py
- static_frame/test/unit/test_store_sqlite.py
The case that prompted this pull request was a dash in the `label` (which becomes table name). You can see the failure by checking out db4a26a and running the `store_sqlite` tests. 
The fix is just to quote the label in generated sql.
> Fix for saving frames to sqlite, when labels contain special characters.

- .github/workflows/quality.yml
- .github/workflows/test.yml
This PR:
- Sets `CFLAGS` to ignore the compiler warnings that were failing Pandas builds for Python 3.8 using Clang (meaning we can test on Python 3.8 / macOS again).
- Adds caching for pip's built wheels, which can reduce the overhead of each run by up to 12 minutes.
- Removes duplicate jobs. Currently, all PR commits run each job *twice*, which takes forever.
In short, it makes CI better and faster. 🙂
> Test using Python 3.8.

- MANIFEST.in
- setup.py
Currently, all symbols imported from `static_frame` in user code are seen by type-checkers as `typing.Any`.
The presence of this file in a distribution indicates to tools like mypy that the annotations in `static_frame` can actually be used when linting user code.
https://mypy.readthedocs.io/en/stable/installed_packages.html#making-pep-561-compatible-packages
> Start shipping a `py.typed` file.

- static_frame/core/bus.py
- static_frame/core/store.py
- static_frame/core/store_zip.py
- static_frame/core/util.py
- static_frame/test/unit/test_store_zip.py
Closes #306 
This turned out to be a relatively simple implementation, as the only use case of max_persist is when there exists an underlying store.
And it just so happens, that the logic for reading in from a store existing only in the base class, effectively meaning only a little bit of extra logic was needing to add this feature. I did end up cleaning up the internals just a little bit, but overall this is a lightweight change in terms of it's impact on the code base.
> Adds a weak_cache to underlying store containers.

- static_frame/core/archive_npy.py
- static_frame/test/unit/test_archive_npy.py
If an ArchiveZip instance fails to instantiate because the filepath it was given doesn't exist, `__del__` raises an `AttributeError` because `_archive` doesn't exist.  The exception is recorded as [unraisable](https://docs.python.org/3/c-api/exceptions.html#c.PyErr_WriteUnraisable) (because it happens in `__del__`?) and is printed to stderr. This adds a test to demonstrate the issue, and fixes it.
> Prevent unhandled exception in ArchiveZip

- static_frame/core/store.py
- static_frame/test/unit/test_bus.py
- static_frame/test/unit/test_store.py
Removes `_weak_cache` from `Store` pickle state to allow pickleing and therefore easier use in multi processing.
https://github.com/static-frame/static-frame/issues/743
> Do not include `_weak_cache` in `Store` pickle state

- static_frame/core/batch.py
- static_frame/core/frame.py
- static_frame/core/interface.py
- static_frame/core/node_selector.py
- static_frame/core/quilt.py
Submitting a tuple to .loc on Compound containers (like Frame) performs a multi-dimensional access. These changes fix the type-hints so that loc/iloc can accept tuples.
```
>>> f
<Frame>
<Index> a       b       c       d       <<U1>
<Index>
0       2       8       4       9
1       3       9       8       2
2       4       10      2       1
<int64> <int64> <int64> <int64> <int64>
>>> f.loc[0, "a"]
2
```
> Fix .loc Type Hints for Compound Containers

- mypy.ini
- static_frame/core/frame.py
pyarrow<1.0 saved parquet files in a format that cannot be loaded by pyarrow>=1.0 unless you add `use_legacy_dataset=True` to the pyarrow.parquet.read_table call. 
This changes adds a fallback to use_legacy_dataset=True if the initial read_table call fails.
Related pyarrow issues:
https://github.com/apache/arrow/issues/32660
https://github.com/apache/arrow/issues/24407
> Support loading parquet files saved with pyarrow<1.0

- doc/source/conf.py
Search was hanging indefinitely because of a sphinx_rtd_theme configuration problem.
Related issue: https://github.com/readthedocs/sphinx_rtd_theme/issues/1452
Example failing:
> Fix Docs Search

- static_frame/__init__.py
- static_frame/core/archive_npy.py
- static_frame/core/frame.py
- static_frame/core/index_base.py
- static_frame/core/series.py
- static_frame/core/util.py
- static_frame/test/unit/test_frame.py
`Frame.to_npz` and `Frame.from_npz` support BinaryIO objects, however its type hint had implied that it only supported Paths.
This change adds typing support (and a test) for BinaryIO objects.
REPL Example of existing functionality:
```
>>> from tempfile import TemporaryFile
>>> f1 = sf.Frame.from_dict_records([{2: 4}, {2: 8}])
>>> with TemporaryFile() as tf:
...     f1.to_npz(tf)
...     f2 = sf.Frame.from_npz(tf)
>>> f1
<Frame>
<Index> 2       <int64>
<Index>
0       4
1       8
<int64> <int64>
>>> f2
<Frame>
<Index> 2       <int64>
<Index>
0       4
1       8
<int64> <int64>
```
> Add `BinaryIO` typing support to `Frame.to_npz`

- static_frame/core/index_base.py
- static_frame/test/typing/test_index.py
Addresses #919
I had a couple of questions since it's my first PR:
- Is it okay to import `IndexBase` in `typing/test_index.py` from the core module? 
- Does the test achieve the desired coverage? (mypy fails upon removal of the code addition to `IndexBase`)
> Add iter_label interface to IndexBase

- static_frame/core/display.py
Addresses #932 
```sh
python static_frame/profile --performance Pivot
```
```
2024-05-10 19:29:46.846978
python:3.11.8|numpy:1.25.2|pandas:2.0.3|static_frame:2.6.0
name                        iterations Native Reference n/r    r/n    win   status explanation
Pivot.index1_columns0_data2 150.0      0.2107 0.3287    0.641  1.5602 True  ✓      
Pivot.index1_columns1_data1 150.0      0.4909 0.6781    0.724  1.3811 True  ✓      
Pivot.index1_columns1_data3 150.0      0.6777 0.8483    0.799  1.2516 True  ✓      
Pivot.index2_columns0_data1 150.0      0.9142 0.6276    1.4567 0.6865 False ✓      
sum                                    2.2936 2.4827    3.6207 4.8794 3.0
min                                    0.2107 0.3287    0.641  0.6865 False
max                                    0.9142 0.8483 …
```
> Update ANSI escape regex
